spring.application.name=url_shortener

#Database connections
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Hibernate configuration
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

app.base-url=${BASE_URL}

#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

spring.cache.type=redis
spring.cache.redis.time-to-live=86400000
